import json
import subprocess
from pathlib import Path
from typing import Any, cast

from fivemanager.backup import create_backup, list_backups, restore_backup
from fivemanager.tmux import start_server, stop_server
from fivemanager.txadmin import build_txadmin_config, load_template, write_txadmin_profile
from fivemanager.wizard import ask_path, prepare_server_paths, run_setup_wizard


def test_backup_prunes_to_three_and_restore_replaces_runtime(tmp_path):
    runtime = tmp_path / "runtime"
    (runtime / "alpine").mkdir(parents=True)
    (runtime / "alpine" / "file.txt").write_text("original")
    (runtime / "txData" / "profile").mkdir(parents=True)
    (runtime / "txData" / "profile" / "config.json").write_text("{}")
    (runtime / "run.sh").write_text("run")

    for index in range(4):
        (runtime / "alpine" / "file.txt").write_text(f"backup-{index}")
        create_backup(runtime)

    backups = list_backups(runtime)
    assert len(backups) == 3
    (runtime / "alpine" / "file.txt").write_text("changed")
    restore_backup(runtime, backups[0])
    assert (runtime / "alpine" / "file.txt").read_text().startswith("backup-")
    assert (runtime / "run.sh").exists()


def test_txadmin_config_generation_and_profile_creation(tmp_path):
    server = {
        "name": "Main RP Server",
        "key": "main-rp",
        "data_path": str(tmp_path / "server-data"),
        "cfg_path": str(tmp_path / "server-data" / "server.cfg"),
    }
    cfg = build_txadmin_config(server)
    assert cfg["general"]["serverName"] == "Main RP Server"
    assert cfg["server"]["dataPath"] == server["data_path"]
    assert cfg["server"]["cfgPath"] == server["cfg_path"]

    profile = write_txadmin_profile(tmp_path / "runtime", server)
    assert profile == tmp_path / "runtime" / "txData" / "main-rp" / "default"
    assert (profile / "data").is_dir()
    assert (profile / "logs").is_dir()
    written = json.loads((profile / "config.json").read_text())
    assert written["general"]["serverName"] == "Main RP Server"


def test_txadmin_template_permission_error_falls_back_to_default(monkeypatch):
    class ForbiddenPath:
        def exists(self):
            raise PermissionError("blocked")

    cfg = load_template(cast(Any, ForbiddenPath()))

    assert cfg["version"] == 2
    assert cfg["general"]["serverName"] == "servername"


def test_txadmin_default_template_path_uses_current_home():
    import fivemanager.txadmin as txadmin

    assert txadmin.TEMPLATE_PATH == Path.home() / ".config" / "fivemanager" / "txadmin-template.json"


def test_ask_path_uses_inquirer_filepath_completion(monkeypatch):
    calls = []

    class FakePrompt:
        def execute(self):
            return " /home/fivem/FiveM-Server "

    class FakeInquirer:
        def filepath(self, **kwargs):
            calls.append(kwargs)
            return FakePrompt()

    monkeypatch.setattr("fivemanager.wizard._inquirer", lambda: FakeInquirer())

    result = ask_path("Runtime path", default="/home/fivem", only_directories=True)

    assert result == "/home/fivem/FiveM-Server"
    assert calls == [{"message": "Runtime path", "default": "/home/fivem", "only_directories": True}]


def test_ask_path_falls_back_to_text_prompt_without_inquirer(monkeypatch):
    monkeypatch.setattr("fivemanager.wizard._inquirer", lambda: None)
    monkeypatch.setattr("builtins.input", lambda prompt: " /srv/fivem ")

    assert ask_path("Runtime path", only_directories=True) == "/srv/fivem"


def test_prepare_server_paths_creates_resources_and_starter_cfg(monkeypatch, tmp_path):
    monkeypatch.setattr("fivemanager.wizard.ask_confirm", lambda *args, **kwargs: True)
    data_path = tmp_path / "new-server"
    cfg_path = data_path / "server.cfg"

    prepare_server_paths("Dev Survival", data_path, cfg_path)

    assert (data_path / "resources").is_dir()
    cfg = cfg_path.read_text()
    assert "Generated by FiveManager" in cfg
    assert 'sv_hostname "Dev Survival"' in cfg
    assert "sv_licenseKey" in cfg


def test_start_server_requires_installed_runtime(monkeypatch, tmp_path):
    monkeypatch.setattr("fivemanager.tmux.session_exists", lambda name: False)
    server_data = tmp_path / "server-data"
    server_data.mkdir()
    cfg_path = server_data / "server.cfg"
    cfg_path.write_text("# config\n")
    server = {"id": 1, "name": "Main", "key": "main", "cfg_path": str(cfg_path), "txadmin_port": 40120, "fxserver_port": 30120}

    try:
        start_server(tmp_path / "runtime", server)
    except RuntimeError as exc:
        assert "missing" in str(exc)
        assert "update-runtime" in str(exc)
    else:
        raise AssertionError("start_server should fail when run.sh is missing")


def test_start_server_requires_server_cfg(monkeypatch, tmp_path):
    monkeypatch.setattr("fivemanager.tmux.session_exists", lambda name: False)
    runtime = tmp_path / "runtime"
    runtime.mkdir()
    (runtime / "run.sh").write_text("#!/bin/sh\n")
    server = {"id": 1, "name": "Main", "key": "main", "cfg_path": str(tmp_path / "missing.cfg"), "txadmin_port": 40120, "fxserver_port": 30120}

    try:
        start_server(runtime, server)
    except RuntimeError as exc:
        assert "Server config does not exist" in str(exc)
    else:
        raise AssertionError("start_server should fail when server.cfg is missing")


def test_setup_wizard_can_bootstrap_brand_new_server(monkeypatch, tmp_path):
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "xdg-config"))
    runtime = tmp_path / "runtime"
    data_path = tmp_path / "server-data"
    cfg_path = data_path / "server.cfg"
    text_answers = iter([
        str(runtime),
        "Dev Survival",
        "devsurvival",
        str(data_path),
        str(cfg_path),
        "40120",
        "30120",
        "0.0.0.0",
    ])
    updates = []
    starts = []

    monkeypatch.setattr("fivemanager.wizard.ask_select", lambda message, choices: "manager" if "What do you want" in message else "done")
    monkeypatch.setattr("fivemanager.wizard.ask_text", lambda *args, **kwargs: next(text_answers))
    monkeypatch.setattr("fivemanager.wizard.ask_path", lambda *args, **kwargs: next(text_answers))
    monkeypatch.setattr("fivemanager.wizard.ask_confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr("fivemanager.wizard.ask_checkbox", lambda *args, **kwargs: [1])

    def fake_update(config, force=False):
        updates.append((config["runtime_dir"], force))
        runtime.mkdir(parents=True, exist_ok=True)
        (runtime / "alpine").mkdir(exist_ok=True)
        (runtime / "run.sh").write_text("#!/bin/sh\n")

    run_setup_wizard(update_callback=fake_update, start_callback=lambda config, sid: starts.append(sid))

    assert updates == [(str(runtime), True)]
    assert starts == [1]
    assert (runtime / "txData" / "devsurvival" / "default" / "config.json").is_file()
    assert (data_path / "resources").is_dir()
    assert cfg_path.is_file()


def test_start_server_builds_expected_tmux_command(monkeypatch, tmp_path):
    calls = []
    monkeypatch.setattr("fivemanager.tmux.session_exists", lambda name: False)
    monkeypatch.setattr(subprocess, "run", lambda args, **kwargs: calls.append(args) or type("R", (), {"returncode": 0})())
    server_data = tmp_path / "server-data"
    server_data.mkdir()
    runtime = tmp_path / "runtime"
    runtime.mkdir()
    (runtime / "run.sh").write_text("#!/bin/sh\n")
    (runtime / "run.sh").chmod(0o755)
    (server_data / "server.cfg").write_text("endpoint_add_tcp '0.0.0.0:30120'\n")
    server = {
        "id": 1,
        "name": "Main",
        "key": "main",
        "cfg_path": str(server_data / "server.cfg"),
        "txadmin_port": 40120,
        "fxserver_port": 30120,
        "interface": "0.0.0.0",
    }

    name = start_server(runtime, server)

    assert name == "fivemanager-1-main"
    cmd = calls[0]
    joined = " ".join(cmd)
    assert "TXHOST_DATA_PATH" in joined
    assert str(runtime / "txData" / "main") in joined
    assert "TXHOST_TXA_PORT" in joined
    assert str(runtime / "run.sh") in joined
    assert "+exec" not in joined
    assert str(server_data) not in joined
    assert "server.cfg" not in joined
